name : node-setup

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: node setup
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Run test
        run: npm test
        

